### ISSUE TITLE
The web site of cncf's sandbox may have a spelling error

### ISSUE THREAD

**Issue by KeHaohaoke** [cncf/contribute#123]
Hi, I found that our DevStream may have a spelling error in the introduction on the CNCF website. It should be Devstream is, not DevStreamis. Can you please correct it? And I found it also exists in several other projects, such as Antrea, Devfile, k8gb, etc. I didn't check all the sandbox projects, please check them all, if there is this problem, it may be better to correct it. Thanks.

![image](https://user-images.githubusercontent.com/103085894/177445952-cb4b5385-2447-4455-9c8e-ee9e1e4abc22.png)

**Comment by carolynvs** [comment]
Can you please include a link to the web page that contains the typo? I'm not sure that this is the right repository, unless it is on https://contribute.cncf.io but with the link we can figure out where to fix it.

**Comment by KeHaohaoke** [comment]
> Can you please include a link to the web page that contains the typo? I'm not sure that this is the right repository unless it is on https://contribute.cncf.io but with the link, we can figure out where to fix it.

Hi, the link to our DevStream sandbox at CNCF is: https://www.cncf.io/projects/devstream/

There are links to other projects that also have errors: https://www.cncf.io/projects/Antrea/, https://www.cncf.io/projects/Devfile, https://www.cncf.io/projects/k8gb, etc., but there may be more than that, so please check them all.

**Comment by carolynvs** [comment]
Okay yeah the cncf.io website is managed in another repository. This repo is for contribute.cncf.io/contributors. I see that you reported this on the onboarding issue for the project, https://github.com/cncf/toc/issues/859#issuecomment-1175234333, and I think that's the best way to get it fixed.

I'm going to close this issue here and we can track the problem under the other issue. Sorry your project got typoed!

**Comment by cjyabraham** [comment]
@KeHaohaoke the spelling issue is [now fixed](https://www.cncf.io/projects/devstream/).
